### PR TITLE
Updated Dutch translation

### PR DESCRIPTION
**Pull request by Vistaus**
:-)

### CODE REVIEW

**Comment by maoschanz** [comment]
I'm still not sure about the pertinence of translating the python3-markdown extensions names, idk what you think about it

**Comment by Vistaus** [comment]
> I'm still not sure about the pertinence of translating the python3-markdown extensions names, idk what you think about it

What extensions/What strings are you referring to?

**Comment by maoschanz** [comment]
"Table of content", "New Line To Break" and "Sane Lists" are currently the only ones i marked as translatable, there are other ones (https://user-images.githubusercontent.com/19996113/72685788-c1b8df00-3aed-11ea-90b3-2174d7e88c0e.png all except the last one)

**Comment by Vistaus** [comment]
I think it's fine to translate them. Maybe you could add a non-translatable tooltip on those strings? E.g.: when you hover the mouse over 'Inhoudsopgave' (Table of content), it displays a tooltip with the actual extension name, i.e. python3-tableofcontent (or whatever it's called).

**Comment by maoschanz** [comment]
The tooltips are the longer strings describing what the extension do, and they are already all translatable and translated (https://github.com/maoschanz/gedit-plugin-markdown_preview/pull/18/files#diff-9ca9f88b2e0e0f2849b99be5d09720a7R44)

I think i'll mark them all as translatable but with comments in the .po(t) files

**Pull request merged**
